<div id="vendor" data-bind="scope: 'customjs'">
    <label for="num1"></label><input type="text" id="num1"/>
    <label for="num2"></label><input type="text" id="num2"/>
    <label for="result"></label><input  id ="result"/>
    <input type="submit" value="Clickme" id="submit">
</div>

<script type="text/x-magento-init">
    {
    	"*": {
                	"myCustomWidget":{}
    	}
    }
</script>


