<div id="vendor" data-bind="scope: 'customjs'">
    <label for="num1"></label><input type="text" id="num1" data-bind="value: num1" />
    <label for="num2"></label><input type="text" id="num2" data-bind="value: num2" />
    <label for="result"></label><input type="text" id ="result" data-bind="value:Number(num1()) + Number( num2())"/>
    <input type="submit" value="Clickme" id="submit" data-bind="click: qty"/>
</div>
<script type="text/x-magento-init">
    {
    	"*": {
        	"Magento_Ui/js/core/app": {
            	"components": {
                	"customjs": {
                    	"component": "Session13Task_CustomJs/js/custom"
                	}
            	}
        	}
    	}
    }
</script>

