<div class="session11task-section" data-bind="scope: 'section'">
    <p data-bind="text: customerdetails().data">Please Log In To See Customer Name</p>
</div>
<script type="text/x-magento-init">
    {
    	"*": {
        	"Magento_Ui/js/core/app": {
            	"components": {
                	"section": {
                    	"component": "Session11Task_Section/js/section"
                	}
            	}
        	}
    	}
    }
</script>
